Docopt arguments
teslaworksumn/midi-lightshow pull request #4
Opened 2017-01-18 21:15 UTC by bookdude13

2017-02-12 00:02 UTC, computergeek125 requested changes

2017-02-12 00:02 UTC, computergeek125 commented on setup.py
>      url='https://github.com/bookdude13/midi-lightshow',
-bookdude13
+teslaworksumn

2017-02-12 19:15 UTC, bookdude13 commented on setup.py
>      url='https://github.com/bookdude13/midi-lightshow',
Addressed

2017-02-13 19:44 UTC, computergeek125 approved these changes

2017-02-13 20:50 UTC, merged